language: node_js
before_script:
  - npm install -g gatsby-cli
node_js:
  - "10"
deploy:
  provider: script
  script: npm install && npm run deploy -r https://$GH_TOKEN@github.com/MooseJ/moosej.github.io.git"
  skip_cleanup: true
  on:
    branch: master