language: node_js
before_install:
  - git config --global user.email "moosejebara@gmail.com"
  - git config --global user.name "Mustafa Jebara"
before_script:
  - npm install -g gatsby-cli
node_js:
  - "10"

script: echo "npm test temporarily disabled"

script: npm install && npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN # Set in the settings page of your repository, as a secure variable
  keep_history: true
  local_dir: public/
  repo: MooseJ/moosej.github.io.git
  target_branch: master
  verbose: true
  on:
    branch: master