language: node_js
before_script:
  - npm install -g gatsby-cli
node_js:
  - "10"

script: echo "npm test temporarily disabled"

script: npm install && npm run build

deploy:
  edge:
    branch: v1.8.47
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN # Set in the settings page of your repository, as a secure variable
  keep_history: true
  local_dir: public/
  repo: MooseJ/moosej.github.io.git
  target_branch: master
  on:
    branch: master